version: '3.9'

services:
  backend:
    build: ./backend
    container_name: reimbursement-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: reimbursement-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # verhindert Konflikt mit lokalen node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
