version: "3.9"

services:
  backend:
    build: ./backend
    container_name: reimbursement-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    # ggf. volumes usw.

  frontend:
    build: ./frontend
    container_name: reimbursement-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
