# Generated by Django 5.2 on 2025-05-03 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_remove_application_amount_applicationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
