# Generated by Django 5.2 on 2025-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_budgetentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationitem',
            old_name='receipt_number',
            new_name='position_number',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ausgezahlt', 'ausgezahlt'), ('genehmigt', 'genehmigt'), ('abgelehnt', 'abgelehnt'), ('entscheidung_ausstehend', 'Entscheidung ausstehen')], default='entscheidung_ausstehend', max_length=30),
        ),
    ]
