# Generated by Django 5.2 on 2025-05-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0006_applicationitem_budget_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='reimbursements.event'),
        ),
    ]
