# Generated by Django 5.2 on 2025-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0008_incomeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='use_case',
            field=models.CharField(choices=[('veranstaltung', 'Veranstaltung'), ('aktivenfahrt', 'Aktivenfahrt'), ('aktivenveranstaltung', 'Aktivenveranstaltung'), ('sonstiges', 'Sonstiges')], default='veranstaltung', max_length=50),
        ),
    ]
