# Generated by Django 5.2 on 2025-05-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0009_application_use_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='application',
            name='use_case',
        ),
        migrations.AddField(
            model_name='applicationitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='reimbursements.event'),
        ),
        migrations.AddField(
            model_name='applicationitem',
            name='use_case',
            field=models.CharField(choices=[('veranstaltung', 'Veranstaltung'), ('aktivenfahrt', 'Aktivenfahrt'), ('aktivenveranstaltung', 'Aktivenveranstaltung'), ('sonstiges', 'Sonstiges')], default='veranstaltung', max_length=50),
        ),
    ]
