# Generated by Django 5.2 on 2025-05-13 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0010_remove_application_event_remove_application_use_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='cashbook_receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursements.application')),
                ('application_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursements.applicationitem')),
                ('income_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursements.incomeentry')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
