# Generated by Django 5.2 on 2025-05-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0012_remove_application_applicant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='purpose',
            new_name='comment',
        ),
    ]
