# Generated by Django 5.2 on 2025-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0013_rename_purpose_application_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='FundingGroup',
        ),
        migrations.RenameField(
            model_name='applicationitem',
            old_name='event',
            new_name='funding_group',
        ),
        migrations.RenameField(
            model_name='budgetentry',
            old_name='event',
            new_name='funding_group',
        ),
        migrations.RenameField(
            model_name='incomeentry',
            old_name='event',
            new_name='funding_group',
        ),
        migrations.RemoveField(
            model_name='applicationitem',
            name='use_case',
        ),
    ]
