# Generated by Django 5.2 on 2025-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0014_rename_event_fundinggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinggroup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
