# Generated by Django 5.2 on 2025-05-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0016_bookingentry_delete_cashbookentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingentry',
            name='income_entry',
        ),
        migrations.RemoveField(
            model_name='bookingentry',
            name='manual',
        ),
    ]
