# Generated by Django 5.2 on 2025-05-18 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0017_remove_bookingentry_income_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='cashbook_receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='reimbursements.application')),
                ('funding_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursements.fundinggroup')),
            ],
            options={
                'ordering': ['booking_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashIncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='cashbook_receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursements.fundinggroup')),
                ('income_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_income_entries', to='reimbursements.incomeentry')),
            ],
            options={
                'ordering': ['booking_date', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='BookingEntry',
        ),
    ]
