# Generated by Django 5.2 on 2025-05-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0019_cashexpenseentry_balance_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashexpenseentry',
            old_name='purpose',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='cashincomeentry',
            old_name='purpose',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='cashexpenseentry',
            name='receipt_file',
        ),
        migrations.RemoveField(
            model_name='cashexpenseentry',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='cashincomeentry',
            name='receipt_file',
        ),
        migrations.RemoveField(
            model_name='cashincomeentry',
            name='receipt_number',
        ),
    ]
