# Generated by Django 5.2 on 2025-05-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0020_rename_purpose_cashexpenseentry_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexpenseentry',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='reimbursements.application'),
        ),
    ]
